VERSION 1.0 CLASS
BEGIN
  MultiUse = 0   'False
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsEffect"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit

'Public Frm As Form

Public Sub UnloadForm()

End Sub

Public Sub LoadForm(ByRef hwndPreviewWindow As Long, _
                    ByRef Left As Long, _
                    ByRef Top As Long, _
                    ByRef Right As Long, _
                    ByRef Bottom As Long)

End Sub

Public Sub ShowDialog()

End Sub

Public Sub FormToSettings()

End Sub

Public Sub SettingsToFrom()

End Sub

Public Sub LoadSettings()

End Sub

Public Sub GetEffectDesc(ByRef IDName As String, _
                         ByRef MenuName As String)

End Sub

Public Sub PerformEffect(ByRef InData() As Long, _
                         ByRef OutData() As Long, _
                         ByRef RangeL As Long, _
                         ByRef RangeT As Long, _
                         ByRef RangeR As Long, _
                         ByRef RangeB As Long)

End Sub

Public Sub SaveSettings()

End Sub

Public Sub SetPreviewWindow(ByRef Frm As frmEffectPreview)

End Sub

